# -*- coding: utf-8 -*-
"""690HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SOE4mS0ZOIVtYtwHKQU5ITqRs_pRR36

#### Assignment 02
 **Author**: Sooyeon Choi **Date**: Feb 7, 2021


 **Requirements**
1. Prompts a user to enter 10 integers.
2. If the user enters anything other than integers, remind her that only integers are allowed and let her retry.
  * Note: You need to detect if use makes a mistake and let the user retry without exiting the program. The previously entered valid inputs should be kept and not lost.

3. Don't allow the user to enter more than 10 or less than 10 integers.

4. Display the 10 integers back to the user at the end.

5. Calculate the following statistics from the 10 integers entered and display the results back to the user:
Minimum
  * Minimum   
  * Maximum
  *  Range
  * Mean
  * Variance
  * Standard Deviation
"""

#Prompting user to create a list of 10 integers

user_inputs = [] #This is the list of the input from the user
while len(user_inputs) < 10: 

  try: 
    user_input = int(input("Please enter an integer (10 times): "))
    print(f"You have entered: ", user_input)
    user_inputs.append(user_input)
  except:
    print("Enter only integer") 

#Finding the range
  maxrange = max(user_inputs)
  minrange = min(user_inputs)
  realrange = maxrange - minrange

#Finding Mean
realaverage = sum(user_inputs) / 10

#Finding Variance
realvariance = sum((i- realaverage)**2 for i in user_inputs) / 10

#Finding Standard Deviation
realsd =  realvariance**0.5

#Print Results
print("You list of numbers are:", user_inputs)
print("Your Maximum number is:", max(user_inputs))
print("Your Minimum number is:", min(user_inputs))
print("Your range is: ", realrange)
print("Your mean is: ", realaverage)
print("Your variance is: ", realvariance)
print("Your standard deviation is: ", realsd)